### ISSUE TITLE
Imputation: meta issue

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#173]
The goal is to roughly reproduce the imputation schemes described in the [PeMS User Guide](https://pems.dot.ca.gov/Papers/PeMS_Intro_User_Guide_v6.pdf). The regression-based scheme is described in more detail in [this research paper](https://pems.dot.ca.gov/Papers/loops_asv2.pdf).

- [x] #169 
- [x] #170 
- [x] ~~#171~~ 
- [x] #172 
- [x] #272

**Comment by ian-r-rose** [comment]
Yes, agree 100% that we should limit regressions to detectors of the same type so that we don't look for correlations between e.g. ramps and mainline.

**Comment by kengodleskidot** [comment]
Just to clarify I think the additional parameters would only be needed if detector data in close proximity is not available. The additional parameters would only be needed if there is no nearby data to correlate with 😊

**Comment by ian-r-rose** [comment]
Agreed!

**Comment by kengodleskidot** [comment]
@ian-r-rose FYI list of station types in PeMS:

CD	Coll/Dist
FF	Fwy-Fwy
HV	HOV
FR	Off Ramp
OR	On Ramp
ML	Mainline
CH	Conventional Highway

**Comment by kengodleskidot** [comment]
I've had a chance to review the imputation paper and associated imputation tables in the PeMS data warehouse. I would like to have a meeting with the group to go over the assumptions in the paper and review the imputation tables in PeMS. Based on the paper and data tables we should be creating a model that stores flow, occupancy and speed coefficients associated with a station and it's neighbor independent of time, see screenshot below:  
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/124397677/d91c2727-bb27-4872-9813-5d9aa3292527)
I believe these coefficients are applied to a formula that incorporates actual values reported by neighbors for a five-minute period which allows for the exclusion of time for the coefficients. When reviewing the paper, the version I have is missing many of the symbols so hopefully there is a cleaner copy out there we can use. I believe the imputation coefficients were updated on a yearly basis from 2012-2017 but has not been updated since. I will follow this up with an email but wanted to document it here future reference.
