### ISSUE TITLE
Create detector status report

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#269]
Based on `int_diagnostics__detector_status`, we should create a human-readable status report which aggregates it up to either the district, or freeway-district combination (or a version of both). This would include things like:

* Number of stations with each status
* Fraction of stations with "good" status
* ...
* ...

cc @kengodleskidot who might have better ideas for nice summary statistics

**Comment by kengodleskidot** [comment]
I think a district wide summary of Good vs. Bad detectors (count and percent) with associated station metadata (County, City, Route, station type) for additional filtering would be great. We should also include a breakdown by error type since this level of detail provides district staff the ability to investigate the cause of a Bad detector status. This can be done on a daily basis since that is the timeframe associated with the detector status. 
The temporal component in summary format would be beneficial as well. A typical example is to look at a user defined timeframe (weeks, months, up to 2 years) and see how many days a detector or detectors have reported a Good vs. Bad status along with associated statuses for the Bad detectors. District staff can then focus on detectors that have reported Bad status more frequently and by type to focus their efforts on how to diagnose/fix detectors.
We do not yet have the detector type (loop, MVDS, camera, etc.) metric available for analysis but we would want to include that as a filtering criterion once it's available.

**Comment by jkarpen** [comment]
@ian-r-rose clarified this issue is to build a mart for detector status, not to build out a dashboard.
