### ISSUE TITLE
Resolve build failure

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#483]
Our nightly job [failed](https://california.getdbt.com/deploy/6/projects/10/runs/6418/) this morning, let's fix it!

**Comment by summer-mothwood** [comment]
Working on it! I believe this failure is due to my attempt to run a full-refresh of one of the marts tables with a changed schema last night. I ran 
`dbt build --target prd --full-refresh --select models/marts/imputation/imputation__detector_summary.sql`

but as per @JamesSLogan , for marts tables you need to specify the analytics_prd database, so the command should be:
`DBT_ANALYTICS_DB=ANALYTICS_PRD dbt build --target prd --full-refresh --select models/marts/imputation/imputation__detector_summary.sql`

I ran that command, which seems to have worked as intended -- the analytics prd database now has the correct schema for the changed mart in Snowflake. I restarted the nightly build, and will monitor/continue to debug if it fails again.

**Comment by summer-mothwood** [comment]
Nightly build re-run was successful.
