### ISSUE TITLE
Production detector metadata is missing

### ISSUE THREAD

**Issue by JamesSLogan** [cagov/caldata-mdsa-caltrans-pems#490]
The detector metadata tables have been truncated, it seems. See:

`select * from raw_prd.db96.detector_config`
`select * from raw_prd.db96.detector_config_log`

This affects essentially all models. The latest data I'm seeing in many models goes to 11-21, so this probably happened some time after the nightly run on the 22nd.

Copies of these tables do exist in `raw_dev`, though I'm not sure how out of date they are.

**Comment by ian-r-rose** [comment]
@pingpingxiu-DOT-ca-gov can you take a look?

**Comment by pingpingxiu-DOT-ca-gov** [comment]
Looking into it!

**Comment by pingpingxiu-DOT-ca-gov** [comment]
The root cause is because during I moving machines / re-provision clusters, service endpoints changed, which lead to bugs. 

* Now, Re-provisioning is done, no more cluster hardware changes. 
* I will fix the bugs introduced by the transition. The service will be expected to be up end of today. 
* Simplify the data relay code. (We should devote a minor bandwidth to continue that.)

@ian-r-rose @ZhenyuZhu-Caltrans

**Comment by pingpingxiu-DOT-ca-gov** [comment]
@JamesSLogan @ian-r-rose @ZhenyuZhu-Caltrans 

The data has been updated to the latest, for the six CONFIG tables.

**Comment by ian-r-rose** [comment]
Thank you!

Ian Rose (he/him)
Principal Data Engineer, Data Services | CA Office of Data and Innovation
(916) 931-8386 | ***@***.***
Follow us: web <https://innovation.ca.gov/> | blog
<https://innovation.ca.gov/blog/> | twitter
<https://twitter.com/californiaodi>

**Comment by jkarpen** [comment]
Closing as resolved per @pingpingxiu-DOT-ca-gov
