### ISSUE TITLE
PeMS detector health diagnostics: no data samples

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#78]
Implement Test number 1 from the [PeMS User Guide](https://pems.dot.ca.gov/Papers/PeMS_Intro_User_Guide_v6.pdf):

<img width="671" alt="image" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/5728311/1f9edd08-7666-4198-bcc1-548b38ecd959">

**Data sources**: 30 second raw data, VDS metadata (controller, station, detector)

**Comment by britt-allen** [comment]
Blocked by #89

**Comment by britt-allen** [comment]
We need to know...

1. Based on raw data samples coming in are we getting the stations that were active for that day?
2. We need to understand the relationship btwn controllers > stations > detectors. Are all not working, are some reporting and some not meaning insufficient data, etc.) We are getting this relationship info from the config files which are still being worked on

**Comment by britt-allen** [comment]
This includes some checks that we don’t have the metadata for yet.

**Comment by kengodleskidot** [comment]
@britt-allen I do not believe we are getting raw samples for every station that is considered "active" on any given day but I will work on a test to confirm this later today (03/14/2024). 
In regard to the controllers > stations > detectors relationships that are contained in the district configuration files, these relationships are also parsed and stored in the data warehouse in the CONTROLLER_CONFIG_LOG, DETECTOR_CONFIG_LOG and STATION_CONFIG_LOG tables. It would be beneficial to understand the structure of these tables so that we can parse the configuration file data in a similar structure once we have a better handle on how to address #75

**Comment by kengodleskidot** [comment]
Based on an analysis of station data in the pems.detector_status table and the INT_CLEARINGHOUSE__STATION_META model in Snowflake Production I believe we have all of the stations that are active on a given date.
